version: "1"

services:
  backend:
    container_name: backend
    image: nhan2947/student-management-api:latest
    restart: on-failure
    build:
      context: ./backend
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    image: nhan2947/student-management-gui:latest
    restart: on-failure
    build:
      context: ./gui
    ports:
      - "5000:5000"
