name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image for StudentManagementAPI
        run: cd StudentManagementAPI && docker build . --file Dockerfile --tag student-management-api:$(date +%s)
        # push the image to docker hub
      - name: Push the Docker image to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker push student-management-api:$(date +%s)
        # I have created a secret in the repository settings with the name DOCKER_USERNAME and DOCKER_PASSWORD.
        # I have also created a repository in Docker Hub with the name student-management-api.
