name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "StudentManagementAPI/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #  connect to ec2 instance and pull the image from docker hub, then run the image
      - name: Connect to EC2 instance and pull the image from Docker Hub
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker pull nhan2947/student-management-api:latest
            docker run -d -p 8080:8080 nhan2947/student-management-api:latest
          '
