name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image for StudentManagementAPI
        run: cd StudentManagementAPI && docker build . --file Dockerfile --tag nhan2947/student-management-api:latest
        # push the image to docker hub
      - name: Push the Docker image to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker push nhan2947/student-management-api:latest
        # I have created a secret in the repository settings with the name DOCKER_USERNAME and DOCKER_PASSWORD.
        # I have also created a repository in Docker Hub with the name student-management-api.

      - uses: actions/checkout@v3
      - name: Build the Docker image for GUI
        run: cd GUI && docker build . --file Dockerfile --tag nhan2947/student-management-gui:latest
        # push the image to docker hub
      - name: Push the Docker image to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker push nhan2947/student-management-gui:latest
        # I have created a secret in the repository settings with the name DOCKER_USERNAME and DOCKER_PASSWORD.
        # I have also created a repository in Docker Hub with the name student-management-gui.

      # connect to ec2 instance
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-91-201-166.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # pull the image from docker hub
            docker pull nhan2947/student-management-api:latest
            docker pull nhan2947/student-management-gui:latest
            # run the image
            docker run -d -p 8080:8080 nhan2947/student-management-api:latest
            docker run -d -p 80:5000 nhan2947/student-management-gui:latest
